name: cd_update_page_on_push

on:
  push:
    branches:
      - main

jobs:
  update-page:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: print where i am
        run: ls
      - name: update page
        uses: ./.github/workflows/update_page.yml@main
        with:
          branch: $GITHUB_REF_NAME
          update2021: false
          update2022: false
          update2023: false
