name: cd_update_page_on_push

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./../

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

  update-page:
    needs: setup
    uses: Kou-ISK/league_one_scraping/.github/workflows/update_page.yml@main
    with:
      update2021: false
      update2022: false
      update2023: false
