name: update page

on:
  schedule:
    # 月曜日の 10:00 (JST) に処理を実行する。
    # UTC の 01:00 は JST だと 10:00 。
    - cron: '0 1 * * 1'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: print where i am
        run: ls

  update-page:
    uses: Kou-ISK/league_one_scraping/.github/workflows/update_page.yml@main
    with:
      update2021: false
      update2022: false
      update2023: false
