name: update page

on:
  schedule:
    # 月曜日の 10:00 (JST) に処理を実行する。
    # UTC の 01:00 は JST だと 10:00 。
    - cron: '0 1 * * 1'

defaults:
  run:
    working-directory: ./

jobs:
  update-page:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: update page
        uses: ./workflows/update_page.yml@main
        with:
          update2021: true
          update2022: true
          update2023: true
