name: update page

on:
  schedule:
    # 月曜日の 10:00 (JST) に処理を実行する。
    # UTC の 01:00 は JST だと 10:00 。
    - cron: '0 1 * * 1'
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./

jobs:
  create-page:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run script
        run: |
          python -m league_one_scraping getInfo 2021
          python -m league_one_scraping getInfo 2022
          python -m league_one_scraping getInfo 2023
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install dependencies for node
        run: npm ci
        working-directory: frontend
      # jsonファイルをもとに静的ページを作成
      - name: Create page from json
        run: npm run deploy-prepare
        working-directory: frontend
      - name: deploy
        run: |
          git checkout -b gh-pages
          git add .
          set -x
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -m 'Deploy page' --no-verify
          git push origin gh-pages --no-verify --force
        working-directory: ./
        env:
          GH_TOKEN: ${{ github.token }}
