name: update page

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      update2021:
        required: true
        type: boolean
      update2022:
        required: true
        type: boolean
      update2023:
        required: true
        type: boolean

defaults:
  run:
    working-directory: ./

jobs:
  update_page:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run script
        run: |
          if [${{inputs.update2021}}]; then
            python -m league_one_scraping getInfo 2021
          fi
          if [${{inputs.update2022}}]; then
            python -m league_one_scraping getInfo 2022
          fi
          if [${{inputs.update2023}}]; then
            python -m league_one_scraping getInfo 2023
          fi
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install dependencies for node
        run: npm ci
        working-directory: frontend
      # jsonファイルをもとに静的ページを作成
      - name: Create page from json
        run: npm run deploy-prepare
        working-directory: frontend
      - name: deploy
        run: |
          git checkout -b gh-pages
          git add .
          set -x
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -m 'Deploy page' --no-verify
          git push origin gh-pages --no-verify --force
        working-directory: ./
        env:
          GH_TOKEN: ${{ github.token }}
