name: update page

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./

jobs:
  get-raw-data:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run script
        run: python -m league_one_scraping
      - run: cat frontend/src/datas/2023_league_one_game_data.json
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install dependencies for node
        run: npm ci
        working-directory: frontend
      # jsonファイルをもとに静的ページを作成
      - name: Create page from json
        run: npm run deploy
        working-directory: frontend
